cli util: Make `jj util exec` act more transparently.
If a subprocess exits with a nonzero status, we don't need to print out
the fact that it exited with a nonzero status.

I think it is fairly obvious that we should try to match the return code
of the inner process.

In a bit more contention is whether we should print out the error
message at all. I would argue that a command that fails almost always
prints to stderr anyway, and the whole point of `jj util exec` is that
it should go into your aliases and thus the fact that it's an "external"
command should be hidden from the user (see my example above).

```
$ jj upload  # "upload" is an alias using jj util exec
<presubmit failures>
Error: presubmits failed
external command exited with 5
<exits with exit status 1>
```